
.global_config: &global_config
  except:
    changes:
      - "README.md"
      - "README.rst"

.build_process: &build_release_job
  <<: *global_config
  image: docker:dind
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script: &build_release_script
    - apk add --no-cache bash git
    - git submodule update --init --recursive
    - chmod +x ./ci/gitlab/build-manylinux.sh
    - ./ci/gitlab/build-manylinux.sh
  artifacts:
    paths:
      - wheelhouse

stages:
  - test
  - build

release_mlinux_wheel:
  <<: *build_release_job
  stage: build
  only:
    refs:
      - master
      - schedules
      - /^release/.*/

test_build:
  <<: *global_config
  image: debian:stable
  stage: test
  script:
    - ./ci/gitlab/install_deb_mirror.sh
    - apt update && apt install -y make curl wget openssh-client openssh-server git cmake libssl-dev zlib1g-dev
    - apt install -y python3 python3-dev python3-distutils
    - wget -O get-pip.py "https://bootstrap.pypa.io/get-pip.py"
    - python3 ./get-pip.py
    - git submodule update --init --recursive
    - python3 setup.py sdist

#~ tests_py3.5:
  #~ <<: *global_config
  #~ image: debian:9
  #~ script:
  #~ - ./tests/scripts/install_root.sh GITLAB 3 5
  #~ - ./tests/scripts/install.sh GITLAB 3 5
  #~ - ./tests/scripts/test.sh GITLAB 3 5
  #~ artifacts:
    #~ paths:
    #~ - htmlcov
  #~ only:
  #~ - master
