
stages:
  - test
  - build

.linux_x86_64_needs: &linux_x86_64_needs
  needs:
    - tests_debstable_x86_64
    - tests_deboldstable_x86_64
    - tests_debtesting_x86_64
    - tests_latest_libssh2_x86_64

.linux_aarch64_needs: &linux_aarch64_needs
  timeout: 6h 30m
  needs:
    - tests_debstable_aarch64
    - tests_deboldstable_aarch64
    - tests_debtesting_aarch64
    - tests_latest_libssh2_aarch64

.osx_needs: &osx_needs
  needs:
    - tests_osx_current
    - tests_osx_10_15

.build_refs: &build_refs
  only:
    refs:
      - master
      - schedules
      - /^release\/.*/
      - build_ci_testing

.build_mlinux_defaults: &build_mlinux_defaults
  <<: *linux_x86_64_needs
  tags:
    - linux
    - x86_64
  image: docker:dind
  services:
    - docker:dind
  variables: &build_mlinux_defaults_variables
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script: &build_mlinux_defaults_script
    - apk add --no-cache bash git
    - git submodule update --init --recursive
  artifacts:
    paths:
      - wheelhouse

.build_osx_process: &build_osx_release_job
  <<: *osx_needs
  tags:
    - osx
    - x86_64
  variables: &build_osx_release_variables
    SYSTEM_LIBSSH2: 1
    DYLD_FALLBACK_LIBRARY_PATH: "./lib"
    #PYTHON_CONFIGURE_OPTS: "--enable-universalsdk=/ --with-universal-archs=intel"
  script: &build_osx_release_script
    - git submodule update --init --recursive
    - ./ci/gitlab/macos/build_wheels.sh
  artifacts:
    paths:
      - wheelhouse


release_mlinux_2010_x86_64_wheel:
  <<: *build_refs
  <<: *build_mlinux_defaults
  stage: build
  script:
    - *build_mlinux_defaults_script
    - ./ci/gitlab/linux/build_manylinux.sh quay.io/pypa/manylinux2010_x86_64
    - ./ci/gitlab/linux/build_manylinux.sh quay.io/pypa/manylinux2010_i686

release_mlinux_2014_x86_64_wheel:
  <<: *build_refs
  <<: *build_mlinux_defaults
  stage: build
  script:
    - *build_mlinux_defaults_script
    - ./ci/gitlab/linux/build_manylinux.sh quay.io/pypa/manylinux2014_x86_64
    - ./ci/gitlab/linux/build_manylinux.sh quay.io/pypa/manylinux2014_i686

release_mlinux_2_24_x86_64_wheel:
  <<: *build_refs
  <<: *build_mlinux_defaults
  stage: build
  script:
    - *build_mlinux_defaults_script
    - ./ci/gitlab/linux/build_manylinux.sh quay.io/pypa/manylinux_2_24_x86_64
    - ./ci/gitlab/linux/build_manylinux.sh quay.io/pypa/manylinux_2_24_i686

release_mlinux_pypy_x86_64_wheel:
  <<: *build_refs
  <<: *build_mlinux_defaults
  stage: build
  script:
    - *build_mlinux_defaults_script
    - ./ci/gitlab/linux/build_manylinux.sh pypywheels/manylinux2010-pypy_x86_64 pypy pypy

release_mlinux_2014_aarch64_wheel:
  <<: *build_refs
  <<: *build_mlinux_defaults
  <<: *linux_aarch64_needs
  tags:
    - linux
    - aarch64
  stage: build
  script:
    - *build_mlinux_defaults_script
    - ./ci/gitlab/linux/build_manylinux.sh quay.io/pypa/manylinux2014_aarch64

release_mlinux_2_24_aarch64_wheel:
  <<: *build_refs
  <<: *build_mlinux_defaults
  <<: *linux_aarch64_needs
  tags:
    - linux
    - aarch64
  stage: build
  script:
    - *build_mlinux_defaults_script
    - ./ci/gitlab/linux/build_manylinux.sh quay.io/pypa/manylinux_2_24_aarch64

#~ release_musllinux_1_1_x86_64_wheel:
  #~ <<: *build_refs
  #~ <<: *build_mlinux_defaults
  #~ stage: build
  #~ script:
    #~ - *build_mlinux_defaults_script
    #~ - ./ci/gitlab/linux/build_manylinux.sh quay.io/pypa/musllinux_1_1_x86_64
    #~ - ./ci/gitlab/linux/build_manylinux.sh quay.io/pypa/musllinux_1_1_i686

#~ release_musllinux_1_1_aarch64_wheel:
  #~ <<: *build_refs
  #~ <<: *build_mlinux_defaults
  #~ <<: *linux_aarch64_needs
  #~ tags:
    #~ - linux
    #~ - aarch64
  #~ stage: build
  #~ script:
    #~ - *build_mlinux_defaults_script
    #~ - ./ci/gitlab/linux/build_manylinux.sh quay.io/pypa/musllinux_1_1_aarch64

release_osx_current_wheel:
  <<: *build_refs
  <<: *build_osx_release_job
  stage: build

release_osx_10_15_wheel:
  <<: *build_refs
  <<: *build_osx_release_job
  variables:
    <<: *build_osx_release_variables
    MACOSX_DEPLOYMENT_TARGET: "10.15"
  stage: build


.cicd_testing_defaults: &cicd_testing_defaults
  stage: test
  tags:
    - linux
    - x86_64
  script:
    - ./ci/gitlab/linux/install_deb_mirror.sh
    - ./ci/gitlab/linux/test.sh GITLAB 3
  variables:
    REDLIBSSH2_BUILD_TRACING: 1
  artifacts:
      paths:
      - htmlcov


tests_debstable_x86_64:
  <<: *cicd_testing_defaults
  image: debian:stable

tests_deboldstable_x86_64:
  <<: *cicd_testing_defaults
  image: debian:oldstable

tests_debtesting_x86_64:
  <<: *cicd_testing_defaults
  image: debian:testing

tests_latest_libssh2_x86_64:
  tags:
    - linux
    - x86_64
  image: debian:stable
  stage: test
  script:
    - ./ci/gitlab/linux/install_deb_mirror.sh
    - ./ci/gitlab/linux/test_latest_libssh2.sh GITLAB
  artifacts:
      paths:
      - htmlcov

tests_debstable_aarch64:
  <<: *cicd_testing_defaults
  <<: *linux_x86_64_needs
  tags:
    - linux
    - aarch64
  timeout: 6h 30m
  image: debian:stable

tests_deboldstable_aarch64:
  <<: *cicd_testing_defaults
  <<: *linux_x86_64_needs
  tags:
    - linux
    - aarch64
  timeout: 6h 30m
  image: debian:oldstable

tests_debtesting_aarch64:
  <<: *cicd_testing_defaults
  <<: *linux_x86_64_needs
  tags:
    - linux
    - aarch64
  timeout: 6h 30m
  image: debian:testing

tests_latest_libssh2_aarch64:
  <<: *linux_x86_64_needs
  tags:
    - linux
    - aarch64
  timeout: 6h 30m
  image: debian:stable
  stage: test
  script:
    - ./ci/gitlab/linux/install_deb_mirror.sh
    - ./ci/gitlab/linux/test_latest_libssh2.sh GITLAB
  artifacts:
      paths:
      - htmlcov


tests_osx_current:
  stage: test
  tags:
    - osx
    - x86_64
  variables:
    <<: *build_osx_release_variables
    PYENV: 3.7.12
  script:
    - *build_osx_release_script

tests_osx_10_15:
  stage: test
  tags:
    - osx
    - x86_64
  variables:
    <<: *build_osx_release_variables
    PYENV: 3.7.12
    MACOSX_DEPLOYMENT_TARGET: "10.15"
  script:
    - *build_osx_release_script


#~ tests_py3.9:
  #~ <<: *cicd_testing_defaults
  #~ image: debian:11

#~ tests_py3.7:
  #~ <<: *cicd_testing_defaults
  #~ image: debian:10

#~ tests_py3.5:
  #~ <<: *cicd_testing_defaults
  #~ image: debian:9


#~ release_windows_wheel:
  #~ <<: *build_release_job
  #~ script:
    #~ - apk add --no-cache bash git
    #~ - git submodule update --init --recursive
    #~ - chmod +x ./ci/gitlab/windows/build.sh
    #~ - ./ci/gitlab/windows/build.sh
  #~ stage: build
  #~ only:
    #~ refs:
      #~ - master
      #~ - schedules
      #~ - /^release\/.*/
      #~ - build_ci_testing
